#Auto generated by Edalize
TARGET        = test_xsim_0
TOPLEVEL      = top_module

VLOG_DEFINES  = --define vlogdefine_bool=True --define vlogdefine_int=42 --define vlogdefine_str=hello
VLOG_INCLUDES = -i .
VLOG_PARAMS   = --generic_top vlogparam_bool=1 --generic_top vlogparam_int=42 --generic_top vlogparam_str=hello

XELAB_OPTIONS =	some xelab_options
XSIM_OPTIONS  = a few xsim_options
