#!/usr/bin/env python
# Copyright FuseSoC contributors
# Licensed under the 2-Clause BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-2-Clause

import os
import sys

with open("vivado.cmd", "a") as f:
    f.write(" ".join(sys.argv[1:]) + "\n")
