#Auto generated by Edalize
TARGET        = test_isim_0
TOPLEVEL      = top_module

VLOG_DEFINES  = --define vlogdefine_bool=1 --define vlogdefine_int=42 --define vlogdefine_str=hello
VLOG_INCLUDES = -i .
VLOG_PARAMS   = --generic_top vlogparam_bool=1 --generic_top vlogparam_int=42 --generic_top vlogparam_str=hello

FUSE_OPTIONS  =	some fuse_options
ISIM_OPTIONS  =	a few isim_options

EXTRA_OPTIONS ?= -testplusarg plusarg_bool=1 -testplusarg plusarg_int=42 -testplusarg plusarg_str=hello
