#Auto generated by FuseSoC

DESIGN_NAME := sockit_0
QUARTUS_OPTIONS := --64bit

qsys:
	ip-generate --project-directory=../../../cores/sockit/data --output-directory=qsys/sockit --report-file=bsf:qsys/sockit/sockit.bsf --system-info=DEVICE_FAMILY="Cyclone V" --system-info=DEVICE=5CSXFC6D6F31C8ES --component-file=../../../cores/sockit/data/sockit.qsys
	ip-generate --project-directory=../../../cores/sockit/data --output-directory=qsys/sockit/synthesis --file-set=QUARTUS_SYNTH --report-file=sopcinfo:qsys/sockit/sockit.sopcinfo --report-file=html:qsys/sockit/sockit.html --report-file=qip:qsys/sockit/sockit.qip --report-file=cmp:qsys/sockit/sockit.cmp --report-file=svd --system-info=DEVICE_FAMILY="Cyclone V" --system-info=DEVICE=5CSXFC6D6F31C8ES --component-file=../../../cores/sockit/data/sockit.qsys --language=VERILOG

	ip-generate --project-directory=../../../cores/sockit/data --output-directory=qsys/sockit --report-file=bsf:qsys/sockit/sockit.bsf --system-info=DEVICE_FAMILY="Cyclone V" --system-info=DEVICE=5CSXFC6D6F31C8ES --component-file=../../../cores/sockit/data/sockit.qsys
	ip-generate --project-directory=../../../cores/sockit/data --output-directory=qsys/sockit/synthesis --file-set=QUARTUS_SYNTH --report-file=sopcinfo:qsys/sockit/sockit.sopcinfo --report-file=html:qsys/sockit/sockit.html --report-file=qip:qsys/sockit/sockit.qip --report-file=cmp:qsys/sockit/sockit.cmp --report-file=svd --system-info=DEVICE_FAMILY="Cyclone V" --system-info=DEVICE=5CSXFC6D6F31C8ES --component-file=../../../cores/sockit/data/sockit.qsys --language=VERILOG
