project_new sockit_0 -overwrite
set_global_assignment -name FAMILY "Cyclone V"
set_global_assignment -name DEVICE 5CSXFC6D6F31C8ES
set_global_assignment -name TOP_LEVEL_ENTITY orpsoc_top
set_parameter -name vlogparam_bool true
set_parameter -name vlogparam_int 42
set_parameter -name vlogparam_str "hello"
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_wb_biu.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_status_reg.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_jsp_biu.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_module.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/syncflop.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_crc32.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_jsp_module.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_top.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/bytefifo.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_biu.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_defines.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/syncreg.v
set_global_assignment -name VERILOG_FILE ../../../cores/adv_debug_sys/../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog/adbg_wb_module.v
set_global_assignment -name VERILOG_FILE ../../../cores/gpio/gpio.v
set_global_assignment -name VERILOG_FILE ../../../cache/jtag_tap_1.13/tap/rtl/verilog/tap_top.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_branch_prediction.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_bus_if_avalon.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_bus_if_wb32.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_cache_lru.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_cfgrs.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_cpu_cappuccino.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_cpu_espresso.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_cpu_prontoespresso.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_cpu.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_ctrl_cappuccino.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_ctrl_espresso.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_ctrl_prontoespresso.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_dcache.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_decode_execute_cappuccino.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_decode.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_dmmu.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_execute_alu.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_fetch_cappuccino.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_fetch_espresso.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_fetch_prontoespresso.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_icache.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_immu.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_lsu_cappuccino.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_lsu_espresso.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_pic.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_rf_cappuccino.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_rf_espresso.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_simple_dpram_sclk.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_store_buffer.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_ticktimer.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_true_dpram_sclk.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_wb_mux_cappuccino.v
set_global_assignment -name VERILOG_FILE ../../../cache/mor1kx_3.1/rtl/verilog/mor1kx_wb_mux_espresso.v
set_global_assignment -name VERILOG_FILE ../../../cache/uart16550_1.5/rtl/verilog/raminfr.v
set_global_assignment -name VERILOG_FILE ../../../cache/uart16550_1.5/rtl/verilog/uart_debug_if.v
set_global_assignment -name VERILOG_FILE ../../../cache/uart16550_1.5/rtl/verilog/uart_receiver.v
set_global_assignment -name VERILOG_FILE ../../../cache/uart16550_1.5/rtl/verilog/uart_regs.v
set_global_assignment -name VERILOG_FILE ../../../cache/uart16550_1.5/rtl/verilog/uart_rfifo.v
set_global_assignment -name VERILOG_FILE ../../../cache/uart16550_1.5/rtl/verilog/uart_sync_flops.v
set_global_assignment -name VERILOG_FILE ../../../cache/uart16550_1.5/rtl/verilog/uart_tfifo.v
set_global_assignment -name VERILOG_FILE ../../../cache/uart16550_1.5/rtl/verilog/uart_top.v
set_global_assignment -name VERILOG_FILE ../../../cache/uart16550_1.5/rtl/verilog/uart_transmitter.v
set_global_assignment -name VERILOG_FILE ../../../cache/uart16550_1.5/rtl/verilog/uart_wb.v
set_global_assignment -name VERILOG_FILE ../../../cache/verilog-arbiter_0-r1/src/arbiter.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/generic_dpram.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/generic_spram.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/timescale.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_clkgen.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_colproc.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_csm_pb.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_cur_cregs.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_curproc.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_enh_top.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_fifo_dc.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_fifo.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_pgen.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_tgen.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_vtim.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_wb_master.v
set_global_assignment -name VERILOG_FILE ../../../cache/vga_lcd_0/rtl/verilog/vga_wb_slave.v
set_global_assignment -name VERILOG_FILE ../../../cache/wb_intercon_1.0/rtl/verilog/wb_arbiter.v
set_global_assignment -name VERILOG_FILE ../../../cache/wb_intercon_1.0/rtl/verilog/wb_data_resize.v
set_global_assignment -name VERILOG_FILE ../../../cache/wb_intercon_1.0/rtl/verilog/wb_upsizer.v
set_global_assignment -name VERILOG_FILE ../../../cache/wb_intercon_1.0/rtl/verilog/wb_mux.v
set_global_assignment -name VERILOG_FILE ../../../cores/sockit/rtl/verilog/clkgen.v
set_global_assignment -name VERILOG_FILE ../../../cores/sockit/rtl/verilog/orpsoc_top.v
set_global_assignment -name VERILOG_FILE ../../../cores/sockit/rtl/verilog/rom.v
set_global_assignment -name VERILOG_FILE ../../../cores/sockit/rtl/verilog/wb_intercon.v
set_global_assignment -name VHDL_FILE ../../../cores/sockit/vhdl_file.vhd
set_global_assignment -name SYSTEMVERILOG_FILE ../../../cores/sockit/sv_file.sv
set_global_assignment -name QIP_FILE ../../../cores/sockit/qip_file.qip
set_global_assignment -name QIP_FILE qsys/sockit/sockit.qip
set_global_assignment -name QIP_FILE qsys/sockit/sockit.qip
set_global_assignment -name SDC_FILE ../../../cores/sockit/data/sockit.sdc
source ../../../cores/sockit/data/pinmap.tcl
set_global_assignment -name SEARCH_PATH ../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog
set_global_assignment -name SEARCH_PATH ../../../cache/mor1kx_3.1/rtl/verilog
set_global_assignment -name SEARCH_PATH ../../../cores/verilog_utils/
set_global_assignment -name SEARCH_PATH ../../../cache/vga_lcd_0/rtl/verilog
set_global_assignment -name SEARCH_PATH ../../../cores/wb_common/
set_global_assignment -name SEARCH_PATH ../../../cores/sockit/rtl/verilog/include
set_global_assignment -name SEARCH_PATH ../../../cores/sockit/rtl/verilog
