#Auto generated by FuseSoC
TARGET        = mor1kx-generic_0
TOPLEVEL      = orpsoc_tb

VLOG_DEFINES  = --define vlogdefine_bool=True --define vlogdefine_int=42 --define vlogdefine_str=hello
VLOG_INCLUDES = -i ../../../cores/adv_debug_sys/Hardware/adv_dbg_if/rtl/verilog -i ../../../cache/mor1kx_3.1/rtl/verilog -i ../../../cores/verilog_utils -i ../../../cores/wb_common -i ../../../cores/mor1kx-generic/rtl/verilog -i ../../../cores/mor1kx-generic/bench/verilog/include
VLOG_PARAMS   = --generic_top vlogparam_bool=1 --generic_top vlogparam_int=42 --generic_top vlogparam_str=hello

XELAB_OPTIONS =	--timescale 1ps/1ps --debug typical dummy options for xelab
