#!/usr/bin/env python
import os
import sys

output_file = sys.argv[2]
with open(output_file, 'a'):
    os.utime(output_file, None)

with open('icepack.cmd', 'w') as f:
    f.write(' '.join(sys.argv[1:]) + '\n')
