#Auto generated by FuseSoC
project new atlys_0
project set family spartan6
project set device xc6slx45
project set package csg324
project set speed -2
project set "Generate Detailed MAP Report" true
project set "Verilog Macros" "vlogdefine_bool=true|vlogdefine_int=42|vlogdefine_str=hello" -process "Synthesize - XST"
project set "Generics, Parameters" "vlogparam_bool=true|vlogparam_int=42|vlogparam_str="hello"" -process "Synthesize - XST"
project set "Verilog Include Directories" "../../../../../.cache/fusesoc/ac97_0/|../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog|../../../../../.cache/fusesoc/ethmac_0/rtl/verilog|../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog|../../../tests/cores/verilog_utils/|../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog|../../../tests/cores/wb_common/|../../../tests/cores/atlys/rtl/verilog/include|../../../tests/cores/atlys/rtl/verilog" -process "Synthesize - XST"
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_cra.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_dma_if.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_dma_req.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_fifo_ctrl.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_in_fifo.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_int.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_out_fifo.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_prc.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_rf.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_rst.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_sin.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_soc.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_sout.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_top.v
xfile add ../../../../../.cache/fusesoc/ac97_0/ac97_wb_if.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/adbg_wb_biu.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_status_reg.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/adbg_jsp_biu.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_module.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/syncflop.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/adbg_crc32.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/adbg_jsp_module.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/adbg_top.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/bytefifo.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_biu.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/adbg_or1k_defines.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/syncreg.v
xfile add ../../../../../.cache/fusesoc/adv_debug_sys_0/Hardware/adv_dbg_if/rtl/verilog/adbg_wb_module.v
xfile add ../../../../../.cache/fusesoc/diila_0/rtl/verilog/diila.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_clockgen.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_cop.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_crc.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_fifo.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_maccontrol.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_macstatus.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_miim.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_outputcontrol.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_random.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_receivecontrol.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_register.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_registers.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_rxaddrcheck.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_rxcounters.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_rxethmac.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_rxstatem.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_shiftreg.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_spram_256x32.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_top.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_transmitcontrol.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_txcounters.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_txethmac.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_txstatem.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/eth_wishbone.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/ethmac.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/ethmac_defines.v
xfile add ../../../../../.cache/fusesoc/ethmac_0/rtl/verilog/xilinx_dist_ram_16x32.v
xfile add ../../../tests/cores/gpio/gpio.v
xfile add ../../../../../.cache/fusesoc/jtag_tap_1.13/tap/rtl/verilog/tap_top.v
lib_vhdl new libstorage_1
xfile add ../../../../../.cache/fusesoc/libstorage_1.0/rtl/vhdl/suv/libstorage_pkg.vhd -lib_vhdl libstorage_1
xfile add ../../../../../.cache/fusesoc/libstorage_1.0/rtl/vhdl/suv/dpram_generic.vhd -lib_vhdl libstorage_1
xfile add ../../../../../.cache/fusesoc/libstorage_1.0/rtl/vhdl/suv/fifo_fwft_adapter.vhd -lib_vhdl libstorage_1
xfile add ../../../../../.cache/fusesoc/libstorage_1.0/rtl/vhdl/suv/fifo_generic.vhd -lib_vhdl libstorage_1
xfile add ../../../../../.cache/fusesoc/libstorage_1.0/rtl/vhdl/suv/fifo_fwft_generic.vhd -lib_vhdl libstorage_1
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_branch_prediction.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_bus_if_avalon.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_bus_if_wb32.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_cache_lru.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_cfgrs.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_cpu_cappuccino.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_cpu_espresso.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_cpu_prontoespresso.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_cpu.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_ctrl_cappuccino.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_ctrl_espresso.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_ctrl_prontoespresso.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_dcache.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_decode_execute_cappuccino.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_decode.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_dmmu.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_execute_alu.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_fetch_cappuccino.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_fetch_espresso.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_fetch_prontoespresso.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_icache.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_immu.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_lsu_cappuccino.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_lsu_espresso.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_pic.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_rf_cappuccino.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_rf_espresso.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_simple_dpram_sclk.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_store_buffer.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_ticktimer.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_true_dpram_sclk.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_wb_mux_cappuccino.v
xfile add ../../../../../.cache/fusesoc/mor1kx_3.1/rtl/verilog/mor1kx_wb_mux_espresso.v
xfile add ../../../tests/cores/ps2/verilog/ps2.v
xfile add ../../../tests/cores/ps2/verilog/ps2_wb.v
xfile add ../../../../../.cache/fusesoc/simple_spi_1.6/rtl/verilog/fifo4.v
xfile add ../../../../../.cache/fusesoc/simple_spi_1.6/rtl/verilog/simple_spi_top.v
xfile add ../../../../../.cache/fusesoc/uart16550_1.5/rtl/verilog/raminfr.v
xfile add ../../../../../.cache/fusesoc/uart16550_1.5/rtl/verilog/uart_debug_if.v
xfile add ../../../../../.cache/fusesoc/uart16550_1.5/rtl/verilog/uart_receiver.v
xfile add ../../../../../.cache/fusesoc/uart16550_1.5/rtl/verilog/uart_regs.v
xfile add ../../../../../.cache/fusesoc/uart16550_1.5/rtl/verilog/uart_rfifo.v
xfile add ../../../../../.cache/fusesoc/uart16550_1.5/rtl/verilog/uart_sync_flops.v
xfile add ../../../../../.cache/fusesoc/uart16550_1.5/rtl/verilog/uart_tfifo.v
xfile add ../../../../../.cache/fusesoc/uart16550_1.5/rtl/verilog/uart_top.v
xfile add ../../../../../.cache/fusesoc/uart16550_1.5/rtl/verilog/uart_transmitter.v
xfile add ../../../../../.cache/fusesoc/uart16550_1.5/rtl/verilog/uart_wb.v
xfile add ../../../../../.cache/fusesoc/verilog-arbiter_0-r1/src/arbiter.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/generic_dpram.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/generic_spram.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/timescale.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_clkgen.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_colproc.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_csm_pb.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_cur_cregs.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_curproc.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_enh_top.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_fifo_dc.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_fifo.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_pgen.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_tgen.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_vtim.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_wb_master.v
xfile add ../../../../../.cache/fusesoc/vga_lcd_0/rtl/verilog/vga_wb_slave.v
xfile add ../../../../../.cache/fusesoc/wb_intercon_1.0/rtl/verilog/wb_arbiter.v
xfile add ../../../../../.cache/fusesoc/wb_intercon_1.0/rtl/verilog/wb_data_resize.v
xfile add ../../../../../.cache/fusesoc/wb_intercon_1.0/rtl/verilog/wb_upsizer.v
xfile add ../../../../../.cache/fusesoc/wb_intercon_1.0/rtl/verilog/wb_mux.v
xfile add ../../../tests/cores/atlys/rtl/verilog/orpsoc_top.v
xfile add ../../../tests/cores/atlys/rtl/verilog/clkgen.v
xfile add ../../../tests/cores/atlys/rtl/verilog/rom.v
xfile add ../../../tests/cores/atlys/rtl/verilog/wb_intercon.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/ddr2_mig.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/infrastructure.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/iodrp_controller.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/iodrp_mcb_controller.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/mcb_raw_wrapper.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/mcb_soft_calibration_top.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/mcb_soft_calibration.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/mcb_ui_top.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/memc_wrapper.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/xilinx_ddr2_if.v
xfile add ../../../tests/cores/atlys/rtl/verilog/xilinx_ddr2/xilinx_ddr2.v
xfile add ../../../tests/cores/atlys/rtl/verilog/dvi_gen/convert_30to15_fifo.v
xfile add ../../../tests/cores/atlys/rtl/verilog/dvi_gen/dcmspi.v
xfile add ../../../tests/cores/atlys/rtl/verilog/dvi_gen/DRAM16XN.v
xfile add ../../../tests/cores/atlys/rtl/verilog/dvi_gen/dvi_encoder.v
xfile add ../../../tests/cores/atlys/rtl/verilog/dvi_gen/dvi_gen_top.v
xfile add ../../../tests/cores/atlys/rtl/verilog/dvi_gen/encode.v
xfile add ../../../tests/cores/atlys/rtl/verilog/dvi_gen/serdes_n_to_1.v
xfile add ../../../tests/cores/atlys/rtl/verilog/dvi_gen/synchro.v
xfile add ../src/atlys_0/data/atlys.ucf
project set top "orpsoc_top"

process run "Generate Programming File"
